### ISSUE TITLE
Scrolling out of sync

### ISSUE THREAD

**Issue by dlccyes** [kinmury/GoldenCoffeeTheme#1]
When opening both edit & preview panes, and scrolling on the edit pane, the preview pane will bug out and wouldn't be in sync.  
Don't have this problem in the base theme or other community themes.  
Basically described in here: https://forum.obsidian.md/t/scroll-out-of-sync-linking-editor-preview-pane/189  

Muy bonita, but this problem is making this unusable.

**Comment by kinmury** [comment]
Thank you for reporting the issue. I have fixed it and now it should be working correctly. I hope you enjoy it :D

**Comment by dlccyes** [comment]
Thanks, it works now!

Great efficiency!
