### ISSUE TITLE
No way to scroll in the options left pane

### ISSUE THREAD

**Issue by gortium** [kinmury/GoldenCoffeeTheme#3]
No way to scroll in the options left pane. When a lot of pluggins are installed, there is no way to access the ones at the bottom.

**Comment by kinmury** [comment]
It's fixed :D

As I said in the Preview Issue, now I know a lot of the problems the "Golden Coffee" theme has, and I'll fix them once I have more free time.

Thank you for your contribution, I really appreciate it :D
